name: UI Tests

on:
  push:
    branches: ["*"] # All branches
  pull_request: # Also run on PRs

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ui

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: ./ui/package-lock.json
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

  ui-tests-label-success:
    needs: test
    if: success() && github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Add "tests-passing" label to PR
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: tests-passing
